In [1]:
import os
import pandas as pd

In [2]:
def get_movie_data():
    
    unames = ['user_id','gender','age','occupation','zip']
    users = pd.read_table(os.path.join('../data','users.dat'), 
                          sep='::', header=None, names=unames)
    
    rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
    ratings = pd.read_table(os.path.join('../data', 'ratings.dat'), 
                            sep='::', header=None, names=rnames)
    
    mnames = ['movie_id', 'title','genres']
    movies = pd.read_table(os.path.join('../data', 'movies.dat'), 
                           sep='::', header=None, names=mnames)

    return users, ratings, movies

In [3]:
users, ratings, movies = get_movie_data()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:9: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:13: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  del sys.path[0]

In [8]:
print(users)

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
5           6      F   50           9  55117
6           7      M   35           1  06810
7           8      M   25          12  11413
8           9      M   25          17  61614
9          10      F   35           1  95370
10         11      F   25           1  04093
11         12      M   25          12  32793
12         13      M   45           1  93304
13         14      M   35           0  60126
14         15      M   25           7  22903
15         16      F   35           0  20670
16         17      M   50           1  95350
17         18      F   18           3  95825
18         19      M    1          10  48073
19         20      M   25          14  55113
20         21      M   18          16  99353
21         22      M   18          15  53706
22         23      M   35           0  90049
23         24      F   25           7  10023
24         25      M   18           4  01609
25         26      M   25           7  23112
26         27      M   25          11  19130
27         28      F   25           1  14607
28         29      M   35           7  33407
29         30      F   35           7  19143
...       ...    ...  ...         ...    ...
6010     6011      M   35          15  80538
6011     6012      M   35          15  02871
6012     6013      F   25          20  32301
6013     6014      M   45           1  80634
6014     6015      F   25           9  80013
6015     6016      M   45           1  37209
6016     6017      F   35           7  21117
6017     6018      M   35           1  48906
6018     6019      M   25           0  10024
6019     6020      M   50          16  10023
6020     6021      M   25          12  08876
6021     6022      M   25          17  57006
6022     6023      M   25           0  43213
6023     6024      M   25          12  53705
6024     6025      F   25           1  32607
6025     6026      M   35           6  11210
6026     6027      M   18           4  20742
6027     6028      M   18           4  94133
6028     6029      F   25           1  23185
6029     6030      M   25          17  32618
6030     6031      F   18           0  45123
6031     6032      M   45           7  55108
6032     6033      M   50          13  78232
6033     6034      M   25          14  94117
6034     6035      F   25           1  78734
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [9]:
print(ratings)

         user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
5              1      1197       3  978302268
6              1      1287       5  978302039
7              1      2804       5  978300719
8              1       594       4  978302268
9              1       919       4  978301368
10             1       595       5  978824268
11             1       938       4  978301752
12             1      2398       4  978302281
13             1      2918       4  978302124
14             1      1035       5  978301753
15             1      2791       4  978302188
16             1      2687       3  978824268
17             1      2018       4  978301777
18             1      3105       5  978301713
19             1      2797       4  978302039
20             1      2321       3  978302205
21             1       720       3  978300760
22             1      1270       5  978300055
23             1       527       5  978824195
24             1      2340       3  978300103
25             1        48       5  978824351
26             1      1097       4  978301953
27             1      1721       4  978300055
28             1      1545       4  978824139
29             1       745       3  978824268
...          ...       ...     ...        ...
1000179     6040      2762       4  956704584
1000180     6040      1036       3  956715455
1000181     6040       508       4  956704972
1000182     6040      1041       4  957717678
1000183     6040      3735       4  960971654
1000184     6040      2791       4  956715569
1000185     6040      2794       1  956716438
1000186     6040       527       5  956704219
1000187     6040      2003       1  956716294
1000188     6040       535       4  964828734
1000189     6040      2010       5  957716795
1000190     6040      2011       4  956716113
1000191     6040      3751       4  964828782
1000192     6040      2019       5  956703977
1000193     6040       541       4  956715288
1000194     6040      1077       5  964828799
1000195     6040      1079       2  956715648
1000196     6040       549       4  956704746
1000197     6040      2020       3  956715288
1000198     6040      2021       3  956716374
1000199     6040      2022       5  956716207
1000200     6040      2028       5  956704519
1000201     6040      1080       4  957717322
1000202     6040      1089       4  956704996
1000203     6040      1090       3  956715518
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [10]:
print(movies)

      movie_id                                              title  \
0            1                                   Toy Story (1995)
1            2                                     Jumanji (1995)
2            3                            Grumpier Old Men (1995)
3            4                           Waiting to Exhale (1995)
4            5                 Father of the Bride Part II (1995)
5            6                                        Heat (1995)
6            7                                     Sabrina (1995)
7            8                                Tom and Huck (1995)
8            9                                Sudden Death (1995)
9           10                                   GoldenEye (1995)
10          11                     American President, The (1995)
11          12                 Dracula: Dead and Loving It (1995)
12          13                                       Balto (1995)
13          14                                       Nixon (1995)
14          15                            Cutthroat Island (1995)
15          16                                      Casino (1995)
16          17                       Sense and Sensibility (1995)
17          18                                  Four Rooms (1995)
18          19              Ace Ventura: When Nature Calls (1995)
19          20                                 Money Train (1995)
20          21                                  Get Shorty (1995)
21          22                                     Copycat (1995)
22          23                                   Assassins (1995)
23          24                                      Powder (1995)
24          25                           Leaving Las Vegas (1995)
25          26                                     Othello (1995)
26          27                                Now and Then (1995)
27          28                                  Persuasion (1995)
28          29                  City of Lost Children, The (1995)
29          30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...
...        ...                                                ...
3853      3923                           Return of the Fly (1959)
3854      3924                                Pajama Party (1964)
3855      3925                      Stranger Than Paradise (1984)
3856      3926             Voyage to the Bottom of the Sea (1961)
3857      3927                            Fantastic Voyage (1966)
3858      3928       Abbott and Costello Meet Frankenstein (1948)
3859      3929                              Bank Dick, The (1940)
3860      3930         Creature From the Black Lagoon, The (1954)
3861      3931                     Giant Gila Monster, The (1959)
3862      3932                          Invisible Man, The (1933)
3863      3933                          Killer Shrews, The (1959)
3864      3934                                      Kronos (1957)
3865      3935                                      Kronos (1973)
3866      3936                   Phantom of the Opera, The (1943)
3867      3937                                     Runaway (1984)
3868      3938                 Slumber Party Massacre, The (1982)
3869      3939              Slumber Party Massacre II, The (1987)
3870      3940             Slumber Party Massacre III, The (1990)
3871      3941                     Sorority House Massacre (1986)
3872      3942                  Sorority House Massacre II (1990)
3873      3943                                  Bamboozled (2000)
3874      3944                                     Bootmen (2000)
3875      3945                          Digimon: The Movie (2000)
3876      3946                                  Get Carter (2000)
3877      3947                                  Get Carter (1971)
3878      3948                            Meet the Parents (2000)
3879      3949                         Requiem for a Dream (2000)
3880      3950                                   Tigerland (2000)
3881      3951                            Two Family House (2000)
3882      3952                              Contender, The (2000)

                              genres
0        Animation|Children's|Comedy
1       Adventure|Children's|Fantasy
2                     Comedy|Romance
3                       Comedy|Drama
4                             Comedy
5              Action|Crime|Thriller
6                     Comedy|Romance
7               Adventure|Children's
8                             Action
9          Action|Adventure|Thriller
10              Comedy|Drama|Romance
11                     Comedy|Horror
12              Animation|Children's
13                             Drama
14          Action|Adventure|Romance
15                    Drama|Thriller
16                     Drama|Romance
17                          Thriller
18                            Comedy
19                            Action
20               Action|Comedy|Drama
21              Crime|Drama|Thriller
22                          Thriller
23                      Drama|Sci-Fi
24                     Drama|Romance
25                             Drama
26                             Drama
27                           Romance
28                  Adventure|Sci-Fi
29                             Drama
...                              ...
3853                   Horror|Sci-Fi
3854                          Comedy
3855                          Comedy
3856                Adventure|Sci-Fi
3857                Adventure|Sci-Fi
3858                   Comedy|Horror
3859                          Comedy
3860                          Horror
3861                   Horror|Sci-Fi
3862                   Horror|Sci-Fi
3863                   Horror|Sci-Fi
3864                          Sci-Fi
3865                          Horror
3866                  Drama|Thriller
3867                 Sci-Fi|Thriller
3868                          Horror
3869                          Horror
3870                          Horror
3871                          Horror
3872                          Horror
3873                          Comedy
3874                    Comedy|Drama
3875  Adventure|Animation|Children's
3876           Action|Drama|Thriller
3877                        Thriller
3878                          Comedy
3879                           Drama
3880                           Drama
3881                           Drama
3882                  Drama|Thriller

[3883 rows x 3 columns]